spring:
  application:
    name: employee

  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sendgrid:
    api-key: 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
    from-email: sales@nixelsoft.com

  security:
    encryption:
      key: VIQ0MB0wYUCYXlAJ9J7Pug==

app:
  frontend-url: http://localhost:3000

API_BASE_URL: http://localhost:8080
