spring:
  application:
    name: employee

  datasource:
    url: jdbc:mysql://localhost:3306/exhibition_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sendgrid:
    api-key: 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
    from-email: sales@nixelsoft.com

  security:
    encryption:
      key: VIQ0MB0wYUCYXlAJ9J7Pug==

app:
  frontend-url: http://localhost:3000

server:
  port: 8080
